### ISSUE TITLE
It seems that Matlab does not have a good support for the pytorch0.4?

### ISSUE THREAD

**Issue by zzpustc** [votchallenge/vot-toolkit#197] opened 2018-10-23 12:55 UTC
When I try to run run_test.m to test my tracker, I got the information in the logs:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zzp/vot-toolkit-master/Focal-space/FocalTrack/track_vot.py", line 12, in <module>
    import torch
  File "/home/zzp/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
RuntimeError: stoi

I am not familiar with the TraX protocol. And it is impossible to degrade pytorch for me. How can I deal with   @bjanssen @jvlmdr @cybertk @AIT-Gustavo-Fernandez @alantrrs

**Comment by lukacu** [comment] 2019-04-08 09:48
I can have a look at this problem, but I would need some kind of Torch 0.4 tracker to test it with, can you recommend one?

**Comment by lukacu** [comment] 2019-04-08 10:01
Also, this looks like a duplicate of #173, we will continue discussion there.

**Closed by lukacu** 2019-04-08 10:01 UTC
Labels: matlab, python
