### ISSUE TITLE
Different results generated when using @trax_wrapper and @system_wrapper

### ISSUE THREAD

**Issue by ArmstrongXing** [votchallenge/vot-toolkit#61] opened 2015-09-02 15:29 UTC
Dear all,
    I have tested my tracker using the toolkit but the obtained results evaluated using @trax_wrapper and  @system_wrapper are quite different. I have spent a lot of time to find the reason for this issue but still cannot figure it out. Have anyone meet a similar issue for this? If have, could you tell me the reason? Or how can I disable @trax_wrapper during evaluation of my tracker?
Thank you in advance!

**Comment by lukacu** [comment] 2015-09-02 16:03
Can you provide an example (trajectory of several frames for each method)? When I was testing the toolkit I tried both methods and they worked identically at the end so I am curios to know what could be the problem in your case.

**Comment by ArmstrongXing** [comment] 2015-09-02 16:16
Yes. I can provide the tracking results on one sequence using the two methods later. I have tested ncc using the two different methods and the results seems to be identical. But for my tracker these two methods differ in about 2% performance drop. This is really brothering. So is there an option to choose which method to evaluate a tracker?

**Comment by lukacu** [comment] 2015-09-02 17:39
Hm, it is not clear about what kind of performance are you talking about ... average overlap? Can you provide trajectory files for both cases so that we can at least determine what could be the problem?

Otherwise I suggest to use the approach that works better, but I would really like to determine the cause of this.

**Comment by ArmstrongXing** [comment] 2015-09-03 07:18
Hi, Lukacu,
I have saved the results on the basketball sequence of our method using the two evaluation methods.
The results are sent to via your email luka.cehovin@gmail.com. 
Or you can try to download it via:
https://onedrive.live.com/redir?resid=4DB69F75E4EEDE8E!986&authkey=!AIPPmfeM1C5uWCI&ithint=file%2czip

At the beginning, the results seems to be the same, with only marginal differences. But the differences accumulates gradually to be very big.

**Comment by lukacu** [comment] 2015-09-03 08:36
I have updated your comment to remove personal information, but I have downloaded the files.

Hm, this is indeed strange. I would understand if the problem would be with reinitialization, but here it seems like the tracker works differently. Even with different rounding the difference should not increase and should be limited to some small value.

Is this a Matlab tracker? Are you working on Windows? Are you using any external libraries that could be problematic? At the moment it seems like there is some kind of internal difference in the tracker caused by the way it is started because the initial frames are all identical and the only other time that the system interacts with the tracker (by giving it an initialization region) is during the initialization. I will need more information to find the reason for this behaviour. I still recommend that you use the one that works better for you at the moment.

**Comment by ArmstrongXing** [comment] 2015-09-03 10:50
Hi, Lukacu,
  Our tracker is written in Matlab with calling OpenCV Matlab package mexOpenCV (http://kyamagu.github.io/mexopencv/). We will re-check our tracker carefully.
Thanks for your advice on evaluating our tracker. We will use system_wrapper to generate the results. But I am just curious to to know that if we upload our tracker for your team to perform evaluation, should it be possible for us to choose system_wrapper to evaluate it?

Thank you again.

**Comment by lukacu** [comment] 2015-09-03 11:02
Yes, please mention this in the report or readme. I will keep an eye on your tracker and try to reproduce the problem so that I can determine the cause. It is a very strange though. I will keep the bug open and report when I will have more information.

**Comment by ArmstrongXing** [comment] 2015-09-03 13:09
OK, thank you very much.

**Comment by lukacu** [comment] 2016-04-20 22:02
Any progress on this issue? Did you manage to find out the reason for the difference? I am cleaning issues for VOT2016 and I would like to know if there is something that I can do regarding the problem since I cannot reproduce it. I will have to close the issue otherwise since we are gradually removing support for system_wrapper anyway.

**Comment by lukacu** [comment] 2016-05-07 20:31
Closing the issue due to inactivity, the problem will be resolved when system_wrapper is removed completely. At the moment we will only display a warning as noted in #68.

**Closed by lukacu** 2016-05-07 20:31 UTC
