### ISSUE TITLE
Tried NCC run_test.m on both Ubuntu 16.04 and MacOS but both reported error "TraX support not detected".

### ISSUE THREAD

**Issue by huanglianghua** [votchallenge/vot-toolkit#158] opened 2018-05-03 04:47 UTC
Hi, I ran scripts on MATLAB in the following order:

```matlab
toolkit_path
workspace_create  % 7, NCC, 1
```

Then I changed the `tracker_NCC.m` as follows:

```matlab
tracker_label = ['NCC'];
tracker_command = generate_matlab_command('ncc', {'/home/user/vot-toolkit/tracker/examples/ncc'});
tracker_interpreter = 'matlab';
```

Everything compiles OK and VOT2017 videos are in the `sequences` folder, but when I ran:

```matlab
run_test  % or run_experiments
```

Error occurred. All output messages are as follows:

```
Initializing workspace ...
Verifying native components ...
Testing TraX protocol support for tracker NCC.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.
Error using tracker_load (line 127)
Tracker has not passed the TraX support test.

Error in run_test (line 8)
tracker = tracker_load('NCC');
```

How can I fix this? Am I missing anything?

**Comment by huanglianghua** [comment] 2018-05-03 04:57
Ah... Finally get things work.

The:

```
tracker_command = generate_matlab_command('ncc', {'/home/user/vot-toolkit/tracker/examples/ncc'});
```

should have been:

```
tracker_command = generate_matlab_command('ncc', {'/home/user/vot-toolkit/tracker/examples/matlab'});
```

**Comment by huanglianghua** [comment] 2018-05-03 05:05
On Ubuntu the above scripts work but on MacOS they still report error "TraX support not detected".

**Comment by lukacu** [comment] 2018-05-03 14:00
Well, we have tested NCC example on MacOS and it works, although I must say that Matlab is a bit slow. Perhaps you may want to increase the trax timeout period. Have you checked the log files?

**Comment by Kewenjing1020** [comment] 2018-05-08 03:08
I tried on MacOS and always fails...

**Comment by lukacu** [comment] 2018-05-08 09:30
Well, that is good to know, but it is not really helpful. As I have said, I cannot reproduce the problem so we will need more information than "the example does not work on Mac". Is there anything in the log files?

**Comment by lukacu** [comment] 2018-05-08 09:33
Btw, there was a small error in the NCC tracker, mentioned in #160, I have fixed it now, so you may check if this was the cause of your problems.

**Comment by Kewenjing1020** [comment] 2018-09-03 12:05
There might be some error in NCC. I download another tracker--[staple](https://github.com/bertinetto/staple.git) and use it test the setup.

**Comment by SmileAngel520** [comment] 2018-09-03 12:18
@Kewenjing1020 Thank you very much. I will try the staple you give. I copy the “tracker.command” to run on the terminal window and it responsed an error following：  
 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
Error using traxserver
Socket information not available. Enable socket communication in TraX client.

Error in vot>tracker_initialize (line 51)
    traxserver('setup', format, 'path');

Error in vot (line 24)
    [handle, image, region] = tracker_initialize(format);

Error in ncc (line 34)
[handle, image, region] = vot('polygon');


I think there maybe something wrong in the ncc.

**Comment by SmileAngel520** [comment] 2018-09-05 15:34
@Kewenjing1020 Hi, I have tried the code you support to me .But I also meet the same problem, can you tell me how you  configure the code?

**Comment by Kewenjing1020** [comment] 2018-09-12 02:34
I think it's the problem of setting up VOT devkit. I suggest you follow the tutorial and setup the devkit again and again, that's what I do.

**Comment by WWWangJie** [comment] 2019-01-05 09:17
When I test the ECO in vot-toolkit, I always meet the problem of Tracker execution interrupted: Unable to establish connection. At first, I think that it's the error of my way. But when I use the ncc, I also meet the problem. And I have changed the version, the problem also come. 
I hope that you can solve my problem, Thank you ! My system is Ubuntu16.04, and I use matlab2017b

**Comment by huanglianghua** [comment] 2019-01-05 10:15
I suggest using the [GOT-10k toolkit](https://github.com/got-10k/toolkit) (https://github.com/got-10k/toolkit) for generating VOT tracking results. It supports VOT2013~2018, and supports supervised, unsupervised as well as real-time experiments, and it's compile-free. The resulting files of the toolkit are directly compatible with vot-toolkit.

**Comment by WWWangJie** [comment] 2019-01-05 12:35
Thanks for your suggestion, I will try it, but I also want to solve this problem, I can run vot-toolkit in windows, now I want to use it in ubuntu16.04.

**Comment by WWWangJie** [comment] 2019-01-05 13:01
And can you tell me how to use install GOT-10k, When I use "pip install --upgrade got10k" to install it, it indicate OSError :[WinError 126]

**Comment by huanglianghua** [comment] 2019-01-05 14:16
`pip install got10k` works for Linux machines (Ubuntu, CentOS, etc.).

For Windows, the `shapely` package (for calculating polygon IoU) used in `got10k` causes [WinError 126].

You can install `shapely` manually first as described  at [this url](https://gis.stackexchange.com/questions/62925/why-is-shapely-not-installing-correctly), then run `pip install got10k`.

**Comment by lukacu** [comment] 2019-04-08 09:08
This thread has gone off-topic, closing.

**Closed by lukacu** 2019-04-08 09:08 UTC
