### ISSUE TITLE
Tracker execution interrupted: Unable to start the tracker process when testing TraX protocol support

### ISSUE THREAD

**Issue by ywangdg** [votchallenge/vot-toolkit#127] opened 2017-06-21 14:35 UTC
Hi, I have just downloaded the vot-toolkit and configured vot-workspace as stated in the tutorials. The process is fine and no problems occur. Then to test it in tracker_NCC.m I set the tracker command as follow:

tracker_command = generate_python_command('python_ncc', {'~/workspace/vot-toolkit/tracker/examples/python/'});
tracker_interpreter = 'python';
tracker_linkpath = {};
tracker_trax = true;

Then I run the run_test command, but the TraX protocol support test failed and the message are as follow:

Trial>> run_test
Initializing workspace ...
Verifying native components ...
Loading sequences ...
Testing TraX protocol support for tracker NCC.
Tracker execution interrupted: Unable to start the tracker process.
TraX support not detected.
Error using tracker_load (line 127)
Tracker has not passed the TraX support test.

I have checked that the directory vot-toolkit/native/trax exists and I did not have compilation problem when creating workspace. So why does the TraX test fails? Should I compile the TraX as in TraX documentation or is there any problem with my tracker integration? I ran the program on Ubuntu 16.04 and Matlab R2017a, with gcc version 4.9.3.

Thank you very much! Waiting for your reply.

**Comment by ywangdg** [comment] 2017-06-21 16:30
Hi, I just checkout to 2016postchallenge version and it works fine with the trax test, could you please check if there's some problems with the latest version? Thanks a lot.

**Comment by lukacu** [comment] 2017-07-01 19:27
Hm, I am not sure why it would work with the previous version, errors related to "Unable to start tracker process" are usually related to problems with tracker startup (e.g. executable not found). Can you try to run the string in the "tracker_command" variable in the terminal to see if you get a @@TRAX:hello message?

**Comment by skyoung** [comment] 2017-07-31 14:26
I got the same problem and I ran the tracker_command in the terminal and got the following message
`@@TRAX:hello "trax.image=path" "trax.region=rectangle" "trax.version=1"`

**Comment by skyoung** [comment] 2017-07-31 14:30
Each time I restart the MATLAB and then run the code, it says `Tracker execution interrupted: Unable to establish connection.`  When I run it again, it says `Tracker execution interrupted: Unable to start the tracker process`

**Comment by skyoung** [comment] 2017-08-01 02:53
I have finally solved this problem.  I forgot to set the "tracker_linkpath" in tracker_XXX.m.

**Comment by lukacu** [comment] 2017-08-02 19:55
As I have said before, the problem is very likely related to tracker startup, the only question is what is the specific problem of each tracker. This is not a toolkit issue as such, perhaps all that we can do is to list the possible causes somewhere.

**Comment by KengChiLiu** [comment] 2017-11-05 16:30
@ywangdg  @lukacu  I still meet the promblem "Tracker has not passed the TraX support test." when evaluating VOT17. Same as you, I have checked that the directory vot-toolkit/native/trax exists and I did not have compilation problem when creating workspace.

tracker_command = generate_matlab_command('SiamFC', {'/home/dspic/code/VOT/siamese-fc/tracking'});
tracker_interpreter = 'matlab';
% tracker_linkpath = {}; 


Output:
Initializing workspace ...
Verifying native components ...
Testing TraX protocol support for tracker SiamFC.
Tracker execution interrupted: Invalid MEX-file '/home/dspic/code/Tool/vot-toolkit/native/traxclient.mexa64': /usr/local/MATLAB/R2016b/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/dspic/code/Tool/vot-toolkit/native/traxclient.mexa64).
TraX support not detected.
Error using tracker_load (line 127)
Tracker has not passed the TraX support test.

Error in run_experiments (line 8)
tracker = tracker_load('SiamFC');


>> tracker_command

tracker_command =

/usr/local/MATLAB/R2016b/bin/matlab -nodesktop -nosplash -r "try; diary 'runtime.log'; addpath('/home/dspic/code/VOT/siamese-fc/tracking');addpath('/home/dspic/code/Tool/vot-toolkit/native/mex');SiamFC; catch ex; disp(getReport(ex)); quit; end;"

**Comment by KengChiLiu** [comment] 2017-11-06 08:23
I've solved the library problem above (GLIBCXX)
However, still showing "Tracker execution interrupted: Unable to establish connection."

>> tracker_command
Undefined function or variable 'tracker_command'.

**Comment by lukacu** [comment] 2017-11-07 22:07
Yes, most likely there is a problem with tracker startup. Unfortunately Matlab trackers are extremely hard to debug when integrated, especially when run on Windows. I think that this issue is ready for closing, these discussions should be continued on the support forum, an issue should only be reopened if there is a well documented problem with the toolkit itself that can be fixed.

**Closed by lukacu** 2017-11-07 22:07 UTC

**Comment by wyukai** [comment] 2019-05-14 00:51
> I have finally solved this problem. I forgot to set the "tracker_linkpath" in tracker_XXX.m.
I also encountered this problem: "Tracker execution interrupted: Unable to start the Tracker process".
Can you tell me how to set "tracker_linkpath" in tracker_xxx.m correctly?
I'm trying to test the RFL on the VOT and hope to get your help.
Thank you very much
