### ISSUE TITLE
Issue while creating workspace using for vot toolkit in  MATLAB 

### ISSUE THREAD

**Issue by pallavivm91** [votchallenge/vot-toolkit#116] opened 2017-05-15 06:10 UTC
Hi 
I am getting the below error while creating the workspace using the new stack 2017 for vot toolkit.

Regards
Pallavi
![error](https://cloud.githubusercontent.com/assets/24267840/26044643/36e60774-3963-11e7-98a6-e58f6fffdd76.png)

**Comment by pallavivm91** [comment] 2017-05-15 17:33
Has anyone faced this issue??

**Comment by lukacu** [comment] 2017-05-18 10:43
Can you paste in an email the output of the following two Matlab commands: `mex -setup C` and `mex -setup C++`? Just as plain text, it is not necessary to send screenshots.

**Comment by pallavivm91** [comment] 2017-05-18 11:40
Hi

I am pasting the output below. It is also attached in the mail. We were
able to do the setup for vot toolkit 2016 but not for toolkit 2017. If you
could figure out why this has happened it will be highly beneficial for us.
[image: Inline image 1]

Regards
Pallavi

**Comment by lukacu** [comment] 2017-05-18 12:45
Hm, the image is missing. Can you please just paste the text without making a screenshot?

**Comment by pallavivm91** [comment] 2017-05-18 13:31
Sorry!

*mex -setup C gives :*

MEX configured to use 'Microsoft Visual C++ 2012 (C)' for C language
compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
variables with more than 2^32-1 elements. In the near future
you will be required to update your code to utilize the
new API. You can find more information about this at:
http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html
.

*mex -setup C++ gives :*
MEX configured to use 'Microsoft Visual C++ 2012' for C++ language
compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
variables with more than 2^32-1 elements. In the near future
you will be required to update your code to utilize the
new API. You can find more information about this at:
http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html
.

**Comment by lukacu** [comment] 2017-05-18 13:50
Since we do not have any computers with VS 2012 to test out the problems the only recommendation is to upgrade your Visual Studio to at least 2013 (we have used this version and verified that compilation works).

**Comment by pallavivm91** [comment] 2017-05-18 17:20
I am facing some issues with 2013 visual studio installation. Will you be
able to share the native folder with us, so that we van directly use the
mex files?

**Comment by lukacu** [comment] 2017-05-18 21:02
A colleague was really helpful and managed to compile toolkit binaries on VS2012 with some modifications that are now merged into the source code of TraX library. You should check if you can compile it now. We have pre-compiled binaries but they do not work as expected since they are cross-compiled for multiple platforms and we are still trying to find the cause for this.

**Comment by pallavivm91** [comment] 2017-05-19 04:14
Hi

Thanks a lot for your corporation. It is working now.

Regards
Pallavi

**Closed** 2017-05-19 08:03 UTC
