### ISSUE TITLE
Unable to compile MEX function

### ISSUE THREAD

**Issue by mariosfourn** [votchallenge/vot-toolkit#179] opened 2018-06-06 18:10 UTC
I'm running the vot-toolkit on an MacOS.10.13.4 and Matlab R2017b and I'm encountering the following error when trying to build a workspace

`MEX completed successfully.
Building with 'Xcode Clang++'.
ERROR: Unable to compile MEX function: "/Users/MF/vot-toolkit/native/trax/support/matlab/traxserver.cpp:83:52: error: ordered comparison between pointer and zero ('trax::Server *' and 'int')
            plhs[0] = mxCreateLogicalScalar(handle > 0);
                                            ~~~~~~ ^ ~
/Users/MF/vot-toolkit/native/trax/support/matlab/traxserver.cpp:155:52: error: ordered comparison between pointer and zero ('trax::Server *' and 'int')
            plhs[0] = mxCreateLogicalScalar(handle > 0);
                                            ~~~~~~ ^ ~
2 errors generated.
".`

Any ideas how to fix this? Thanks

**Comment by alanlukezic** [comment] 2018-06-11 06:46
The toolkit and trax communication were tested on the MacOS (high sierra) and Matlab 2017 where compiling was successful. Currently we do not have an access to the Mac machine which means that we are not able to reproduce the error. Do you use the latest toolkit version?

**Comment by mariosfourn** [comment] 2018-06-11 12:02
Yes, I have the latest toolkit version.  Any ideas about anything I could
try?

**Comment by mariosfourn** [comment] 2018-06-11 14:38
HI, I fixed the issue by replacing `(handle > 0)` with `(handle =! NULL)`. Although I can't be certain that this may not mess up something else further down the line.

**Comment by alanlukezic** [comment] 2018-06-12 12:42
Nice to hear that you found the solution. I think that whether experiments perform normally (the sequence is fully evaluated and failures are detected) the toolkit should work properly.

**Comment by lukacu** [comment] 2019-04-08 09:07
Closing issue, the change has been made.

**Closed by lukacu** 2019-04-08 09:07 UTC
