### ISSUE TITLE
Matlab crashes every time I stop a run_test.m

### ISSUE THREAD

**Issue by mariosfourn** [votchallenge/vot-toolkit#185] opened 2018-08-14 11:25 UTC
I have the latest version of the vot-tookit and Matlab Matlab2018a (9.0.4) on MacOS 10.13.6.

I have downloaded the ECO trackers  and I'm testing it on sequences from the 2017 dataset. Every time I close the pop-up windows with the tracker's output superimposed on the current frame, Matlab crashes.

I sent a crash report to Matlab they responded that according to the stack trace, it appears that the crash is caused by one of the MEX files created by the Third Party Toolbox: 'traxclient.mexmaci64'. 

Also downgrading to Matlab2017b solves the problem.

**Comment by mariosfourn** [comment] 2018-08-14 19:17
I sent a crash report to Matlab they responded that according to the stack trace, it appears that the crash is caused by one of the MEX files created by the Third Party Toolbox: 'traxclient.mexmaci64'.

**Comment by lukacu** [comment] 2018-08-28 13:08
Hi, at the moment we do not have any Matlab 2018a instances so we cannot confirm or investigate this issue, however, we will try to do it as soon as we get a suitable system. It is strange that it works in older versions and not in 2018.

**Comment by ihpdep** [comment] 2018-11-06 20:28
crash on Matlab 2018 too

**Comment by sunshinefly** [comment] 2019-01-07 02:50
crash on Matlab 2018 too...........

**Comment by lukacu** [comment] 2019-04-08 15:15
I can confirm that the toolkit indeed crashes on Matlab 2018+, I have tested it on Matlab 2019a and it looks like the problem is rooted in some undocumented Matlab functionality that worked ... up to 2018 versions. Now it causes a lot of problems, so the safest bet at the moment is to use Matlab 2017 or lower. This will probably even speed up our migration to a Python-based toolkit as there are simply too many issues with Matlab.

**Comment by lukacu** [comment] 2019-04-15 08:41
Ok, we have fixed this problem (at least I have tested it and it works) in the dev branch which should be merged soon. Closing the issue.

**Closed by lukacu** 2019-04-15 08:41 UTC
Labels: matlab

**Comment by meetdave06** [comment] 2019-10-24 05:55
It crashed for me on R2019a as well. It would be very helpful if the fixes are merged to the master.
