### ISSUE TITLE
run_analysis error

### ISSUE THREAD

**Issue by thias15** [votchallenge/vot-toolkit#83] opened 2016-05-31 12:04 UTC
Error using matlab.graphics.axis.Axes/set
While setting the 'YLim' property of 'Axes':
Value must be a 1x2 vector of numeric type in which the second element is larger than the first and may be Inf

Error in report_difficulty (line 112)
    set(gca, 'YLim', [0, max(result.robustness.normalized(:))], ...

Error in report_challenge (line 128)
    difficulty_document = report_difficulty(context, trackers, sequences, experiments, 'uselabels', true, 'usepractical', true);

Error in run_analysis (line 15)
report_challenge(context, experiments, trackers, sequences); % Use this report for official challenge report

**Comment by alanlukezic** [comment] 2016-05-31 12:25
Have you checked VOT Challenge support forum?
https://groups.google.com/forum/?hl=en#!forum/votchallenge-help
There are some issues regarding analysis described and solved. If your problem still exists we will need more information about the error: system, platform, toolkit version...
Also, try to put a breakpoint on the line where error appears and check the content of the structure result.

**Comment by lukacu** [comment] 2016-09-01 14:54
Any new details on this issue? Since it looks a very specific error without much details on how to reproduce it, I will close the issue if no new details will become available.

**Comment by lukacu** [comment] 2016-09-13 19:55
Closing because no further details were provided.

**Closed by lukacu** 2016-09-13 19:55 UTC

**Comment by xubin19939** [comment] 2019-04-11 08:28
> Closing because no further details were provided.

since there are still some bugs in this benchmark,I wanna use benchmark 2018 or 2017 for test for now.but I haven't find these links,could you tell me where can download these benchmarks.thanks

**Comment by xubin19939** [comment] 2019-04-11 08:29
@lukacu since there are still some bugs in this benchmark,I wanna use benchmark 2018 or 2017 for test for now.but I haven't find these links,could you tell me where can download these benchmarks.thanks
