### ISSUE TITLE
The field'channels'that does not exist is referenced.

### ISSUE THREAD

**Issue by MZYGSX** [votchallenge/vot-toolkit#230] opened 2019-05-09 11:01 UTC
When i run the run_test, i met the question.  
CLIENT: Trying to terminate process nicely.
CLIENT: Escalating to brute-force termination.
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (stopped by signal 15)
CLIENT: Closing server socket.
Tracker execution interrupted:The field'channels'that does not exist is referenced. 。
The field'channels'that does not exist is referenced.

error workspace_test>callback (line 79)
        if ~all(ismember(state.channels, fieldnames(data.sequence.channels)));

error tracker_run (line 77)
    data = traxclient(tracker.command, callback, ...

error workspace_test (line 54)
            tracker_run(tracker, @callback, data);

error run_test (line 10)
workspace_test(tracker, sequences);

**Comment by lukacu** [comment] 2019-05-10 09:34
Can you be more specific, which stack are you using? Which OS?

**Comment by MZYGSX** [comment] 2019-05-10 10:16
I'm sorry! My stack is VOT-TIR2015,My OS is win10，the version of matlab is matlab 2016a.
The problem I encountered before was that "The field'analysis'that does not exist is referenced."when i run the run_analysis.
 Later, I used the latest version of the vot-toolkit to solve that question,but I encountered this problem when running run_test.

**Comment by lukacu** [comment] 2019-06-04 10:07
Sorry for the delay. I am unable to reproduce the issue. Hopefully you have resolved it somehow, I will look at it some more when I have time.

**Comment by lukacu** [comment] 2019-10-16 09:48
I assume this has been resolved, closing the issue.

**Closed by lukacu** 2019-10-16 09:48 UTC
